using System;

namespace TradingBacktester.Models
{
    /// <summary>
    /// Represents a trading signal generated by a strategy
    /// Tells us when to buy or sell based on analysis
    /// </summary>
    public class TradeSignal
    {
        // CORE DATA PROPERTIES
        public DateTime Date { get; init; }
        public TradeAction Action { get; init; }  // Buy or Sell
        public decimal Price { get; init; }       // Price when signal was generated
        public string Reason { get; init; }       // Why this signal was generated

        // CONSTRUCTOR
        public TradeSignal(DateTime date, TradeAction action, decimal price, string reason)
        {
            Date = date;
            Action = action;
            Price = price;
            Reason = reason ?? "No reason provided";
        }

        // DEBUG FUNCTIONS
        public override string ToString()
        {
            var actionText = Action == TradeAction.Buy ? "BUY" : "SELL";
            return $"{Date:yyyy-MM-dd} {actionText} at {Price:C} - {Reason}";
        }
    }
}